# Generated by Django 4.2.6 on 2023-11-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_work_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('about', models.TextField()),
            ],
        ),
    ]
